test:
  workers:
    type: local
    number: 1
  rounds:
    - label: Initiate Overtake
      txDuration: 50
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: benchmarks/overtake/overtakeBenchmark.js
        arguments:
          vehicleId: "OV001"
          leadVehicleId: "LV001"
          followingVehicleId: "FV001"


monitors:
  resource:
    - module: docker
      options:
        interval: 5
        containers:
          - all
      charting:
        bar:
          metrics: [Memory(avg), CPU%(avg)]
        polar:
          metrics: [all]
    - module: process
      options:
        interval: 3
        processes:
          - { command: 'node', arguments: 'caliper', multiOutput: 'avg' }
      charting:
        bar:
          metrics: [all]
